### ISSUE TITLE
How to get it running on a Pi Zero W ?

### ISSUE THREAD

**Issue by Eleonorus** [philippe44/AirConnect#107]
Hi all,

I would love to get AirConnect on a Pi Zero W running and failed with all my attempts. (Btw, I am not an Linux expert).

May you have any hints how to fix the issue?

Tried installation at 15 Sep 2018 on a Pi Zero W with this CPU and Linux:

root@raspberrypi:/var/lib/airconnect# cat /proc/cpuinfo
processor       : 0
model name      : ARMv6-compatible processor rev 7 (v6l)
BogoMIPS        : 697.95
Features        : half thumb fastmult vfp edsp java tls
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xb76
CPU revision    : 7
Hardware        : BCM2835
Revision        : 9000c1
Serial          : 000000005c2571e1

Raspbian GNU/Linux 9. It came with OpenSSL 1.1.0f  25 May 2017

I tried OpenSSL in various versions: 
libssl1.0.0_1.0.1t-1+deb8u9_armhf.deb, 8u7, 7u4. 

No success at all. 

Error message:
Sep 15 12:20:35 raspberrypi systemd[1]: Starting AirUPnP bridge...
-- Subject: Unit airconnect.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit airconnect.service has begun starting up.
Sep 15 12:20:35 raspberrypi systemd[1]: airconnect.service: Control process exit
Sep 15 12:20:35 raspberrypi systemd[1]: Failed to start AirUPnP bridge.
-- Subject: Unit airconnect.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- Unit airconnect.service has failed.
--
-- The result is failed.
Sep 15 12:20:35 raspberrypi systemd[1]: airconnect.service: Unit entered failed
Sep 15 12:20:35 raspberrypi systemd[1]: airconnect.service: Failed with result '

Manual execution of the command gives "illegal instruction".

sudo /var/lib/airconnect/airupnp-arm -l 1000:2000 -z -f /var/log/airupnp.log
Illegal instruction

**Comment by philippe44** [comment]
It works on my pi 1A+ which has the same CPU. Here is my Linux system
`Linux raspberrypi 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
OpenSSL 1.0.1t  3 May 2016`
I tried aircast-arm (the arm5 does not work due to older glibc version)

**Comment by philippe44** [comment]
Isn't this what you're looking for https://downloads.raspberrypi.org/raspbian_lite_latest ?

**Comment by macecchi** [comment]
Were you able to download libssl 1.0.0 @Eleonorus ? I'm trying to install on a Pi 1B+ but the link that the README refers to returns a 404: http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u8_armhf.deb

I was a bit confused on where to find the correct version for armv6l. I tried downloading a version from the link below but it gave me `Illegal instruction` when running aircast:
http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u9_armhf.deb
@philippe44 where could I find the correct distribution of that lib? Or, better yet, why can't we use the version of libssl that comes installed, is it hard upgrading?
Thanks!

**Comment by gitti046** [comment]
Hi philippe44,

i tried to get air-connect running on a raspi1 as well as on a raspi2. Both are on the latest rasbian version (Debian 9.4 based). Openssl is installed by default in version 1.1.0f on this distribution.

In both cases i was not able to get air-connect running (error message: illegal instruction). I guess this is due to the openssl version. On my MAC with Mojave air-connect runs perfectly.

As the openssl version air-connect requires is a little bit outdated, the problem that air-connect does not run on actual systems will increase over the time. 

So the question to you (as macecchi asks in the comment before) is, wether it is possible to use newer openssl libraries.

It would be very kind if you think about this request :-)

Thx in advance and greetings from Germany!
Jens

**Comment by philippe44** [comment]
I forgot to update the link but the wget was correct. The problem with using newer openssl librairies is

1/ it's a lot of work as I need re-cross-install all these
2/ there will pobably even more people unhappy b/c AirConnect will not work out-of-the box with distro

So I agree that with time I will do the move, I'm just not sure when is the right time

**Comment by Semidio** [comment]
I tried http://mirrordirector.raspbian.org/raspbian/pool/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u9_armhf.deb and it works for me.

**Comment by gitti046** [comment]
Hi Semidio,

i think it's not a question wether your mentioned version works. Philippe44 stated in his first post in this thread, that that is the version, he uses too. The problem is, that in case you install newer distri's and you install some application which require openssl as well, the package manager will install newer versions of libssl than 1.0.1t. In my case i guess it is "iobroker", which requires openssl. and there seems no easy way back to an older version....

Or do you (or some of the readers) know a way to "downgrade" or a way to install two versions of openssl/libssl in parallel?

Jens

**Comment by philippe44** [comment]
Oh I see - please use a proper installation (as said in the README, using dpkg) to add older openssl version and then they will co-exist peacefully

**Comment by philippe44** [comment]
Close for inactivity
