### ISSUE TITLE
Question: What happens if the host IP address changes?

### ISSUE THREAD

**Issue by pwt** [philippe44/AirConnect#144]
I'm observing that AirConnect (airupnp) will stop working if the host IP address changes. This is for long-running AirConnect processes on devices which have dynamic IP addresses. AirConnect does not crash, but no AirPlay targets are shown to client devices. I assume this is the expected behaviour.

If so, is there a way to check for IP address changes and for AirConnect to accommodate the change?

Thanks.

**Comment by philippe44** [comment]
It's a tough one. I have a dedicated Start() and Stop() function and a master thread, but calling the Stop() function is really made to do *full* cleanup before exiting so I would need to modify these so that they don't start/clean everything, but just what is needed. 
I would also have to detect the IP change in the master thread. I'm not sure there is not lots of side effects doing that. It's complicated, candidly, mainly due to to the amount of tests that I would have to run. Do you think there are so many cases were PC dynamically assigned IP addresses are re-assigned with a different value at the end of the lease?

**Comment by stephenjharrington** [comment]
Most routers have the ability to always allocate the same IP address to a specific device based on its MAC address. Look for “DHCP Reservation” or similar, although different manufacturers use their own naming to describe the same thing ... would possibly be a much easier way to fix the issue?

**Comment by pwt** [comment]
Hi @philippe44 That sounds great. Very happy to do some testing.

@stephenjharrington Yes, I'm familiar with how routers handle IP allocation. For this use case, I'm thinking about third party contexts where the user may be non-technical and just wants something that's plug'n'play.

**Comment by philippe44** [comment]
Hi @ pwt - any progress with your tests?

**Comment by pwt** [comment]
@philippe44 : Apologies, I'd not spotted the commit. (It's tiresome that GitHub doesn't alert for commits to watched repositories.) Thanks for the work on this: I'll start testing today.

**Comment by pwt** [comment]
On testing, airupnp now successfully accommodates an IP address change on DHCP lease renewal. I've tested it through two address changes. Any active streams will stop, as expected, but the service as a whole keeps running.

Testing was performed with airupnp running in a Docker container on a Raspberry Pi 3.

Thanks the great work on this. I'll close the issue.
