### ISSUE TITLE
Aircast-x86-64 always consuming little CPU even when idle

### ISSUE THREAD

**Issue by viboux** [philippe44/AirConnect#149]
Here are the first process in my top command. I have aircast-x86-64 running with -Z -k options in a Debian stretch based Docker inside of Ubuntu 18.04.2 LTS. The docker is used for compatibility reason.

What I see is that aircast-x86-64 is always consuming a little CPU (between 0.7% and 1.3%) and always on the top in a idle system even if it's doing nothing. The CPU usage does go up when I use it to stream. There are many other idle servers (node, etc) doing nothing and they are not using CPU at all. Is it normal? Is the application waiting actively on a socket or something? Memory usage on the other side is absolutely great.

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                               
 1119 root      20   0 1476976  42908  24668 S   0.7  0.3   0:05.82 containerd                                                                            
 8079 root      20   0  340304   4032   3584 S   0.7  0.0   0:03.66 aircast-x86-64                                                                        
 1242 root      20   0 1416668  94972  38300 S   0.3  0.6   0:44.07 dockerd

**Comment by philippe44** [comment]
Yes I know there is a small amount of CPU used. The application has some running threads which are difficult to fully put in sleep so they are waking regularly and go to sleep immediately. I could force the wake up to be much less often but then responsiveness would be affected. I’ll look at that again, but AFAIR, it was difficult to change this. Never know, a fresh look after a while might give me better ideas

**Comment by philippe44** [comment]
I checked again. It's the fact that I have to use select on a socket wher eI'm waiting for RTSP connection. It should be just an accept() but unfortunately, accept() will block and there is no way to exit it if user wants to terminate the app or the player disconnects, the thread is blocked. So I need to use select() with a small timeout and a loop. I know I could use 2 sockets and have one "signalling" one to cause exit when needed, but that was more complicated

**Comment by philippe44** [comment]
With version 0.2.6.0 you should see a significant reduction of CPU consumption when idle

**Comment by viboux** [comment]
Just downloaded 0.2.6.1 and running it now. Idle CPU consumption is much much better. Good job!

Looked at your changelog. Seems like a very complicated fix. Unfortunately I am not that good with threading in C. Can you just listen() on a socket? Or once you have an active Airplay speaker you need to keep the socket more active?

**Comment by philippe44** [comment]
Excellent - Can you share some figures?

The way sockets work in that case, is that you have to set port and make a listen(). I do that for every detected CC device. Then, for each of them, I create a thread that is in charge of waiting for AirPlay request. These threads normally do an accept() which blocks until a client establishes a connection.

The problem is when you want to terminate that thread (CC disconnected or exiting aircast), on all platform except FreeBSD, if you shutdown() the listening socket, then the accept() exits (there are debates about the proper behavior). But on FreeBSD? you're stuck in accept().

So because of that, I replaced the accept() by a select() with a 50ms timeout, so the waiting thread was looping every 50ms. When the select() was indicating a connection, I was doing and accept() which was not blocking. But that 50ms busy loop was not great (although afaik, a lot do that). Increasing it was not a much better solution.

Anyway, I finally decided to move back to an accept() and to force exit it on termination, I create a "fake" self-connection that I immediatey close. Not pretty either but much more CPU efficient and seems to work on all platform.
