### ISSUE TITLE
try run it on android tv device, however it says "sh: ./system/bin/airupnp-arm: No such file or directory"

### ISSUE THREAD

**Issue by bigsquirrel** [philippe44/AirConnect#157]
Hi philippe44,

I am trying run the airupnp on my android tv devices(xiaomi mini box, MT8685, armv7). When i try to excute the program, the shell stop with error msg "sh: ./system/bin/airupnp-arm: No such file or directory". But i am sure it currently be there.

root@forrestgump:/system/bin # pwd
/system/bin
root@forrestgump:/system/bin # ./airupnp-arm
sh: ./airupnp-arm: No such file or directory

-rwxrwxrwx root     root       481800 2019-04-11 22:36 airupnp-arm

**Comment by philippe44** [comment]
It’s not compiled to run under android, even if it’s just a modified Linux. It might say file not found because some libraries are not accessible and I would guess that’s OpenSSL because that’s the only one dynamic load. I need a version 1.0.x, see README. Even with that I would be surprised that it’d work

**Comment by philippe44** [comment]
closed for inactivity

**Comment by Yamazaki-Youichi** [comment]
@bigsquirrel 
Perhaps it has solved but just for your information I run Ubuntu on the Android (fire tv) terminal and succeeded in using Airconnect.
https://github.com/EXALAB/Anlinux-Resources
