### ISSUE TITLE
make into mac app?

### ISSUE THREAD

**Issue by yonigold1** [philippe44/AirConnect#161]
Any way for someone to make this into a mac app? it would be such a help for noobs like me

**Comment by philippe44** [comment]
Sorry, I really know nothing about macOS development; Being to compile my apps for it was already a serious stretch

**Comment by stephenjharrington** [comment]
Personally I use airupnp-osx-multi with a customised com.aircast.bridge.plist so that it auto-starts on my Mac Mini server, and that works very well for me (thanks Phillippe!) however ... before I discovered AirConnect I did trial the commercial macOS application "AudioBridge" from https://audiobridge.site/ which appeared to do more or less the same thing with a fancy front-end from the brief trial I gave it, although with a lot less flexibility in terms of custom configuration, at the small cost of USD $14.99. So maybe download the trial?

But seriously, with the documentation here it wasn't that hard to get AirConnect going and doing what I wanted, so maybe persevere and you may have fun and learn something along the way?

Cheers,

StephenH

**Comment by philippe44** [comment]
Just one thing: AudioBridge is a front-end to my apps, which is great, but the dev did not follow changes, so he is still using a very old version (1.5.1)

**Comment by stephenjharrington** [comment]
VERY old then! Thanks Phillippe.

**Comment by yonigold1** [comment]
> Personally I use airupnp-osx-multi with a customised com.aircast.bridge.plist so that it auto-starts on my Mac Mini server, and that works very well for me (thanks Phillippe!) however ... before I discovered AirConnect I did trial the commercial macOS application "AudioBridge" from https://audiobridge.site/ which appeared to do more or less the same thing with a fancy front-end from the brief trial I gave it, although with a lot less flexibility in terms of custom configuration, at the small cost of USD $14.99. So maybe download the trial?
> 
> But seriously, with the documentation here it wasn't that hard to get AirConnect going and doing what I wanted, so maybe persevere and you may have fun and learn something along the way?
> 
> Cheers,
> 
> StephenH

perhaps u can help me set mine up? :D

**Comment by stephenjharrington** [comment]
> perhaps u can help me set mine up? :D

Honestly I just bumbled my way through until I got a result, but I'm sure people here with a lot more knowledge than me can assist :-)

**Comment by philippe44** [comment]
Look at the README, it gives you almost all you need for OSX

**Comment by philippe44** [comment]
Would you mind closing this one?

**Comment by philippe44** [comment]
Closed for inactivity
