### ISSUE TITLE
Playing through USB Audio Device

### ISSUE THREAD

**Issue by FlyingTrashcan** [philippe44/AirConnect#190]
Thank you for such a great app that is super easy to install and get running!  I'd like to try and run this from a Raspberry Pi0 wireless.  I'm testing on a Raspberry Pi3b and I am now unable to get the audio to play out of a connected USB device, instead of the onboard audio.  I image there is a setting for this, but I can't seem to find it.  My USB device is showing up, and I can get system sounds to play out of the speakers, but not from AirConnect.  

Thoughts?

Thank you!

Joe

**Comment by philippe44** [comment]
Sorry I don't understand your setup. AirConnect needs a UPnP or a Chromecast device to send audio to, it's a bridge. It does not send audio to a soundcard

**Comment by FlyingTrashcan** [comment]
Sorry about that.  I installed AirConnect on a Raspberry Pi, and I use AirPlay from my iPhone to stream audio to it.  If I plug into the stereo jack on the Raspberry Pi, I can hear the Airplay audio.  Maybe this is outside of the intended use, but it seems to be working almost perfectly for what I was hoping.

**Comment by philippe44** [comment]
No AirConnect does not do that. You either have an AirPlay client like shairport on your pi and you stream to it or you have a UPnP player on your pi and AirConnect recognizes it. But I can guarantee you that AirConnect does not send audio to sound card directly

**Comment by jelockwood** [comment]
@FlyingTrashcan 
As @philippe44 indicates the audio coming from the built-in port is not due to AirConnect but a happy accident. What you could try doing is firstly get the USB device working completely separate to AirConnect. Once you have got it working see if there are any options to get it working as the primary built-in audio interface or to have both working simultaneously.

If your luck continues then the happy accident of the music being played will then work via the USB port.

Certainly until you get the USB port working by itself there will be no chance of it working with AirConnect.

**Comment by philippe44** [comment]
Closed for inactivity
