### ISSUE TITLE
AirUPNP: ALAC support

### ISSUE THREAD

**Issue by Gummibando** [philippe44/AirConnect#20]
Please add ALAC "passthrough" support.

My streamer supports the ALAC codec, so it basically does not need transcoding and could be fed the ALAC codec'ed audio stream from AirPlay directly.

**Comment by philippe44** [comment]
It's not possible because on the RTP side, it's a succession of 8 ms alac-encoded frames and on the HTTP side this would have to be decoded and re-packaged in a mp4 container. I thought about that at the beginning, but stopped because of that. There is no fidelity loss in the transcoding and it's not too much CPU hungry, so it's a minor inconvenience

**Comment by Gummibando** [comment]
Ah, stupid me. This makes total sense.  I falsely assumed the stream could be used as-is but as you mentioned it obviously has to be repackaged for HTTP. WAV ist totally fine :)
