### ISSUE TITLE
AirUPNP: Any possibility for meta data?

### ISSUE THREAD

**Issue by Gummibando** [philippe44/AirConnect#21]
Is there any possibility for the transmission of meta data (track info)?

**Comment by philippe44** [comment]
Unfortunately no - AirPlay sends a continuous stream of audio in RTP frames and some metadata information using the RTSP channel. The Metadata are timestamped relatively to RTP frames so that a player knows when to start displaying them (typically when a new track starts). UPnP is totally different and do not accept metadata "on the flow". It must be sent when a playback starts, together with the stream information. All what is sent by AirPlay is seen as a single very long track by UPnP
