### ISSUE TITLE
Files in /bin downloaded as textedit, how to open?

### ISSUE THREAD

**Issue by Frsm** [philippe44/AirConnect#23]
I am unable to execute aircast-osx-multi it downloads as textfile. I added .dmg but that didn't work.

**Comment by marco79cgn** [comment]
Just remove the wrong file ending so that your file is just named "airupnp-osx-multi" (without extension). You can't simply double click the file anyway. In order to execute it, you have to make it executable (as mentioned in the ReadMe - chmod +x).

You can try to start all over again do the following on Mac OS X:
1. Open the Terminal (e.g. via Spotlight)
2. In Terminal, execute the following commands (Press Return after each)
```
cd
mkdir airconnect
cd airconnect
curl https://raw.githubusercontent.com/philippe44/AirConnect/master/bin/airupnp-osx-multi -o airupnp-osx-multi
chmod +x airupnp-osx-multi
./airupnp-osx-multi -l 250:500
```
This will create a new folder in your user folder named airconnect. It will download the binary for Mac OS X, make it executable and start it.
