### ISSUE TITLE
[Improve] - mediar render on home fist connect

### ISSUE THREAD

**Issue by corrpel** [philippe44/AirConnect#247]
Hi,
Can we improve the app by creating the media render on the GH device as soon as we chose the airplay speaker from IOS menu.
What i saw is when you connect, only after you play something i get the chime on google home meaning that the session is created.
I believe that this will improve the latency from what i saw.
Because if we press play then pause for sometime, after we press play again the audio/video sync is right there.
I know that you said that no much can be done to improce delay, but this ca be a thing that can help.
Maybe have this as an option in .xml file?!
Also, is just a question (i don't know if that can be done), but can we measure what content is in airplay queue and how much is in the http, and if the difference is big, trim from http in the begining in order to be much closer to sync?
Thank you.

**Comment by philippe44** [comment]
Loading the renderer as soon as the AirPlay speaker is selected means that as soon as the RTSP session is opened. That would create all sort of interoperability issues with other GH controller as well as with other AirPlay controller. 
As I said previously, sync is not a reliable option for AirConnect so I don't want to go that route just to have more frustrated/confused users because "it almost works ... except when it does not"

**Comment by corrpel** [comment]
Ok, i understand this. Anyway, this app looks very good and i don't think that something close to it exist.
Thank you for your hard work!
