### ISSUE TITLE
Terminal not running after these lines

### ISSUE THREAD

**Issue by dennisyjz** [philippe44/AirConnect#359]
Hi,

I'm running on the latest version of Mac OS Big Sur and it seems that after following the guide, the executable only runs three lines and then gets stuck. What might be going wrong here?
`[19:59:54.815479] main:1420 Starting airupnp version: v0.2.50.5 (May 24 2021 @ 15:14:58)`
`[19:59:54.816141] main:1428 no config file, using defaults`
`[19:59:54.817051] Start:1130 Binding to 192.168.1.125:49152`

**Comment by philippe44** [comment]
It's not stuck but no device is detected

**Comment by shmkane** [comment]
Wanted to add that I'm having the same results on a Windows 10 Home (OS Build 19042.1052).

Running through WSL Ubuntu 20.04 produces the same output as well.
I've tried disabling my Firewall as well as allowing the ports listed, no difference.

**Comment by pwt** [comment]
> Wanted to add that I'm having the same results on a Windows 10 Home (OS Build 19042.1052).
> ...
> UPDATE: Seems to be working fine on my Mac mini that's wireless. Wonder if being wired has something to do with it. Wondered if @dennisyjz is also wired

For some reason, your speakers are not being discovered. This is usually because the SSDP multicast discovery packets aren't reaching the interface that AirConnect is bound to. Typical reasons for this:

1. Firewall
2. Defective router that does not forward multicast packets between its wired and wireless interfaces
3. Sonos system on a different subnet or VLAN

Obviously, in your case, I'd check out #2.

**Comment by philippe44** [comment]
Closed for inactivity
