### ISSUE TITLE
Expected audio lag

### ISSUE THREAD

**Issue by fantapop** [philippe44/AirConnect#36]
Great work on this project.  I just had a quick question.  I'm running AirConnect as you mention in the readme with the 1 second RTP buffer and the 2 Second Http buffer.  I was expecting that to create a lag of 3 seconds for obvious reasons.  I'm running VLC and inserting a lag under the Track Synchronization settings so that can watch video.  The synchronization lag that works is 4 seconds. I'm wondering if you have any idea why this is or if theres something different I should be doing.

**Comment by philippe44** [comment]
The [rtp] parameter does not add any delay, only the [http] does. Are we talking about AirCast or AirUPnP? In any case, you can't control the playback delay because it's HTTP. What [http] does is *adding* some silence that is used as a buffer for players that do not do a good job at buffering (Sonos), but the player can still add their own delay for buffering (Chromecast do). So the actual delay will be [http] + [whatever the player add which might +/- 0.5s or so]
