### ISSUE TITLE
I run AirConnect on a Asus router, but the IP address is not correct.

### ISSUE THREAD

**Issue by guokai10000** [philippe44/AirConnect#369]
I manage to run AC on AX-86U with airupnp-arm5, but the IP address  is bound to the WAN IP, which is 192.168.1.2.

But the LAN IP should be 192.168.50.1, so what should I do if I want it to run in LAN?

Thank you.

**Comment by philippe44** [comment]
Use -b option (see README)

**Comment by jrahkala** [comment]
I think i got it working now. I had to uncheck "Multicast Enable". I thought it should be enabled, but it seems it must be disabled? Thank you very much for the link!

Now I have a differerent problem. My Ubuntu Desktop works OK, but Ubuntu Server does not. AirConnect seems to work just fine on Ubuntu Server when i run "aircast-x86-64" and see the output. But when I run "aircast-x86-64 -z" so that it runs in the background and after that list my sinks with "pacmd list-sinks" there is just my servers own sound card present. Very strange. I have similar machines as a Ubuntu Desktop installation and Ubuntu Server installations. "Pulseaudio" and "pulseaudio-utils" are installed.

**Comment by guokai10000** [comment]
Many thx for your reply philippe44, but now I encountered another problem.
I run airupnp-arm5 -z -x config.xml meanwhile I have changed the name of my speaker.
But the name appears different on iPhones and iPads. 
Sometimes they are the changed ones, sometimes they are the original ones.

**Comment by philippe44** [comment]
How did you change the name?

**Comment by guokai10000** [comment]
I downloaded and edit the config.xml <name> </name> part. Then I uploaded the file to the server.
However, now the problem seems being solved. The names are  correct since I wake up today morning.

发自我的iPad
