### ISSUE TITLE
Unable to play correctly on Cambridge Audio Stream Magic 6 v1

### ISSUE THREAD

**Issue by vmasseron** [philippe44/AirConnect#470]
# Problem
Unable to stream to uPnP device except in mp3 format where it only work for a few seconds.
Under as much information as possible:

# Setup
## AirConnect
Version: v1.1.7 (May 20 2023 @ 06:12:13)
I've tried to run AirConenct from:

- my M1 Pro mac
- an arch64 VM

Results are the same.
On bothe cases, **I used the static version, can this change anything ?**

## Source
I tried to play from:
- Qobuz on my M1 Pro mac
- Qobuz  on my iPohne X
- Spotify on my iPohne X

## Renderer
I want to render on a Cambridge Audio Stream Magic 6 v1. This player supports uPnp.
The product is no more on the manufacturer website but I foud that about supported formats:
```
Format supporté
    WAV (PCM, 16-24 bits, 32- 96 kHz)
    FLAC (PCM, 16-24 bits, 32- 96 kHz)
    AIFF (PCM 16 bits, 32- 48 kHz)
    Micorsoft WMA 9, MP3 (CBR ou VBR, 32-320 kbps)
    AAC, HE AAC et AAC+, OGG Vorbis
```
from https://www.homecinesolutions.fr/p/10230-cambridge-audio-stream-magic-6-noir

This player have WiFi and Ethernet but **I only tried WiFi, can this change anything ?**

# Tests
For the tests, I used AirConnect from my mac and used my iPhone with Qobuz, added little latency, 

- `./airupnp-macos-arm64-static -c wav -d all=sdebug -l 1000:2000 >wav.log 2>&1`
Show "streaming from AirCinnect" for less than  a sec then show "End of the queue" ont the player screen
[wav.log](https://github.com/philippe44/AirConnect/files/11594330/wav.log)

- `./airupnp-macos-arm64-static -c mp3 -d all=sdebug -l 1000:2000 >mp3.log 2>&1`
Sound for a few seconds (maybe 3 to 4), on the screen: "Straming from AirConnect", "Unknow song, Unknow artist", time elapsed in sec, "MP3 128kbps", after it stopped playing, only "Streaming from AirCOnnect" and "End of the queue"
[mp3.log](https://github.com/philippe44/AirConnect/files/11594320/mp3.log) 

- `./airupnp-macos-arm64-static -c flac -d all=sdebug -l 1000:2000 >flac.log 2>&1`
"Streaming from AirConnect" on the screen but no sound at all
[flac.log](https://github.com/philippe44/AirConnect/files/11594337/flac.log)

- `./airupnp-macos-arm64-static -c pcm -d all=sdebug -l 1000:2000 > pcm.log 2>&1`
"Streaming from AirConnect" on the screen but no sound at all
[pcm.log](https://github.com/philippe44/AirConnect/files/11594340/pcm.log)

- I've tried using the `--noflush` workaround without sucess
- I've tried tweak with the `-g` without sucess neither
- I'v tried increase latency by a lot without sucess
- I don't think there is any firewall

# End word
I really want to make it work, if you need any more information don't hesitate, thank you !

**Comment by philippe44** [comment]
It's been a while but I totally overlooked that issue, sorry about that. From the log, it seems to be one of this unfortunately classic issue I have been facing with players that have a faulty HTTP/UPnP stack. I'll explain in case you are interested.

When a client requests a resource from a server using HTTP, it shall **not** assume that the server knows the length of that resource and/or has it buffered. HTTP in itself has *standardized* ways for a server to tell the client "here is what I have, but I don't know the length of the file. HTTP 1.1 went even further with a explicit transfer mode named "chunked-encoding".  The client should **never** assume that the length is know and should **never** assume that by asking twice the same resource, it will get the same result - this is particularly true for audio. 

Furthermore, UPnP adds a layer that allows the server to explicitly tell the client *in advance* : "hey, this resource has a moving head and/or a moving tail, so don't assume anything".

Still, some software developers can't care to read specs and think that a HTTP resource is always available so they ask "just the first 128kB of data". Of course, this does not end well because when they ask again either the first 128kB of data or the whole resource, then they are surprised because they don't receive the same thing they received the first time... and/or they don't like that when they ask for a range, the server responds with the fully body although the HTTP standard clearly says that a range-request can be ignored and the server can answer with the full body. Sorry clients, I know it's a pain (sometimes I'm on the other side of the request), but that's what the standard says and there is a reason why we have standards :smile:

So all this is bad programming. First, the UPnP headers are sent *before* the HTTP request is made, so the client **knows** it's a live resource. Then, if you decide to ignore UPnP and just rely on HTTP, you should expect such live stream so ask for the whole resource and see what comes back *or* do a HEAD request *or* memorize what you have already received and stitch things together.

Can I do workarounds? Yes, I can memorize things and try to guess what the client expects but every time I've tried that it bit me in the butt because some other clients did not like that "guessing" game and I ended up punishing good behaving clients for the benefits of rogue ones.

Is my code flawless, far from that to say the least. But being the guy doing free software I can't be the one "liable" for crap left by people charging $$$$$$ for faulty boxes and refusing to fix their them.

Please, don't get me wrong, this is not a rant against you at all :smile:

**Comment by philippe44** [comment]
Having said that, and to make sure I'm contradicting and embarrassing myself while confirming being bitten every time I try to workaround these problems, I've issued a 1.2.0 that does something for those players that ask for 0-xxx (128000 in your case) ranges multiple times. Let's see how much damage I did

**Comment by vmasseron** [comment]
First thanks a lot for all you have done/are doing !
Second, thanks a lot for these details, I know better understand whats going on.

I've just tried with the 1.2.0 but I sadly got the same result (ie. only a few seconds of sound and "End of queue" on the player). I'v tried tweaking `-g` option but the result is the same.
Under the debug outputs:


`./airupnp-macos-arm64-static -c mp3 -g 0 -d all=sdebug -l 1000:2000 >mp3g0.log 2>&1`
[mp3g0.log](https://github.com/philippe44/AirConnect/files/12566401/mp3g0.log)

`./airupnp-macos-arm64-static -c mp3 -g -1 -d all=sdebug -l 1000:2000 >mp3g1.log 2>&1`
[mp3g1.log](https://github.com/philippe44/AirConnect/files/12566403/mp3g1.log)

`./airupnp-macos-arm64-static -c mp3 -g -3 -d all=sdebug -l 1000:2000 >mp3g3.log 2>&1`
[mp3g3.log](https://github.com/philippe44/AirConnect/files/12566404/mp3g3.log)


Please understand that I'm already very grateful for this, feel free to answer tonight, next year or even never if you want to.

**Comment by philippe44** [comment]
Unfortunately the changes I've made obviously does not matter for that player. Something strange is that it does not behave as it did a few month ago in your initial log. This changes, if they where actioned, would have generated a specific log, but there is nothing and still, it HTTP requests are a bit different. Was there a firmware update?

**Comment by philippe44** [comment]
oh, can you try flac as well?

**Comment by vmasseron** [comment]
I've would have been very surprised by an update, it's an unmaintained product by years :)

The log for flac test in 1.2.0
For each it plays for something like half a second and stops.

./airupnp-macos-arm64-static -c flac -g 0 -d all=sdebug -l 1000:2000 >flacg0.log 2>&1
[flacg0.log](https://github.com/philippe44/AirConnect/files/12567805/flacg0.log)

./airupnp-macos-arm64-static -c flac -g -1 -d all=sdebug -l 1000:2000 >flacg1.log 2>&1
[flacg1.log](https://github.com/philippe44/AirConnect/files/12567806/flacg1.log)

./airupnp-macos-arm64-static -c flac -g -3 -d all=sdebug -l 1000:2000 >flacg3.log 2>&1
[flacg3.log](https://github.com/philippe44/AirConnect/files/12567808/flacg3.log)

**Comment by philippe44** [comment]
So unfortunately it did not change a thing. It really seems these devices don't understand that range-request don't have to be answered with a range response. Sorry, but I don't know what else to do.

**Comment by vmasseron** [comment]
It's sad, but anyway. Thanks for time you spend on this issue.
If you have any idea later don't hesitate to re-open the issue.
