### ISSUE TITLE
Screen-mirroring

### ISSUE THREAD

**Issue by tschuerti** [philippe44/AirConnect#527]
I would love to mirror my screen to my Chromecast or just airplay a video to it. Unfortunately it only supports sound :( But great Programm!

**Comment by SoPat712** [comment]
<img width="675" alt="image" src="https://github.com/philippe44/AirConnect/assets/30350506/9469b0fd-0b06-493a-9f9a-3ace3edc4dd8">

**Comment by nathan815** [comment]
> This is an audio-only application. Do not expect to play a video on your device and have the audio from UPnP/Sonos or ChromeCast synchronized. It does not, cannot and will not work, regardless of any latency parameter. Please do not open tickets requesting this ***(see details below to understand why)***

@SoPat712  This is talking about syncing video on a device with audio streaming to speakers via AirConnect. How about streaming video & audio directly to a Chromecast device via AirConnect? I believe that is what was being asked here and I am looking to do this too.

For example: I am watching a video on my iPhone. I click the AirPlay button and select my Chromecast TV, then the video & audio starts playing there.

**Comment by SoPat712** [comment]
Sorry, yes, that specific screenshot was related to syncing on device video with streamed audio, but the point still stands that there doesn't seem like there are ever plans to implement video and audio. It does seem like a cool idea though.

Unfortunately, I'm pretty sure that AirConnect was only ever intended to just facilitate the **_audio_** transport from your device via the server to your Chromecast/UPnP player. I don't believe the project maintainer ever wants to add video either, so that's probably for some other project to implement, or if you think it's something you could help with, the project seems to be accepting contributions.

Personally, I use Replica for this, let me know if that seems to fit your needs!

**Comment by nathan815** [comment]
That makes sense. I will look at Replica. Thanks for the recommendation!

It would be pretty neat to have Chromecast devices automatically show up as AirPlay video devices on the network, but that's probably pretty challenging to implement.
