### ISSUE TITLE
AirPlay 2 support?

### ISSUE THREAD

**Issue by kleagon** [philippe44/AirConnect#53]
Is this something possible for a future release?
Thank you so much for such a great work with this project.

**Comment by torange** [comment]
I was hesitant to open this up as an issue, since it’s really more of a feature request. It should be feasible once the AirPlay 2 code is made available, but I don’t know if anyone has published it yet. Now that it’s available in iOS 11.3, on Apple TV and HomePod, I’m sure it’ll trickle out sooner or later.

**Comment by philippe44** [comment]
I have no idea at this point if apple will release their protocol. I wish that Google foes that for their CC sync protocol. I know Sonos will not, but it's unfortunate Google does not either ... they release all the rest

**Comment by torange** [comment]
iirc, the original airplay protocol was reverse engineered from an airport express. Perhaps we’ll see something along the same lines with an Apple TV (or other device) & AirPlay 2.
