### ISSUE TITLE
Compiling on Windows needs clarification

### ISSUE THREAD

**Issue by miho** [philippe44/AirConnect#6]
First of all, thanks for your project!

Since there's no Makefile for Windows it would be great to get some hints on how to compile on Windows. 

From the dlls I guess you use a Borland C++ compiler. Is that right?

**Comment by philippe44** [comment]
Yes, I use Embarcadero (BorlandC++) XE7. I realize the Windows compilation is not the easiest thing to do, because you also need libupnp, libflac, alac, pthread and need to chose if you want them as static or shared libs or simply part of the compilation. In addition, XE7 does not allow anymore to generate a makefile from its projects so there is not much I can do here. I would recommend taking example of the other systems makefile and adapt it to VC. If you are using BorlandC++. I can provide a project

**Comment by miho** [comment]
Borland/Embarcadero offers a free version. That's why I think it would be great if you'd publish your BorlandC++ project. This gives other devs the opportunity to play with your code. Thanks!

**Comment by philippe44** [comment]
ok, give me a couple of weeks, I'm away currently (I need to clean a bit this project file from all sort of absolute path

**Comment by philippe44** [comment]
I've added my project files, "as is". I will not really maintain them, but you can start from these. You'll need to still download all the other source code that comes from other repositories, including flac and upnp. I can't provide more at that time
