### ISSUE TITLE
bin dir permissions

### ISSUE THREAD

**Issue by relytmcd** [philippe44/AirConnect#73]
permissions in bin directory - why aren't there execute permissions in the bin directory?

Also thanks!

**Comment by philippe44** [comment]
It's because it's zipped on a Windows platform

**Comment by relytmcd** [comment]
got it, thanks, want to change that?

**Comment by philippe44** [comment]
Is this a request or an offer for help? My script is using 7-zip on Windows and although I've never looked really, but I'm not sure there is a way to do that

**Comment by relytmcd** [comment]
Offer for help in the guise of a “do you mind if i suggest something”, I’ll take a look at the script and see if theres something to do.

**Comment by philippe44** [comment]
Suggestions always welcome! :-). The "script" is silly as invoking 7-zip on a directory and sub-dir. The problem is that the compilation is on a Linux box doing cross-compiling (except for Windows and MacOS) and files are stored on a NAS that is then accessed by Win7 using SMB (NAS runs samba) for being zipped. So I don't think that the Unix rights can be preserved.

**Comment by philippe44** [comment]
I can't do that but you gave me an idea. Although I'm using git desktop from Windows for the commits (I've not done proper scripts for that part), I can still change the file mode for the executables. So I've done that, I just hope they'll stick between commits. It does not solve the problem for people downloading the zipped file from sourceforge, but when you get the individual ones from githuib directly, that should work - thanks for the suggestion

**Comment by relytmcd** [comment]
Excellent, thanks!
