### ISSUE TITLE
Stream stops and app not responding

### ISSUE THREAD

**Issue by ghost** [philippe44/AirConnect#82]
Hay

After about 1 a 2 minutes of playing the stream stops en de app isn't responding, also the virtual airplay devices are gone. Had this installed on a r-pi and a ubuntu 16.04 system

**Comment by philippe44** [comment]
You have to tell a bit more and add a log (I can't help with just once sentence saying "it does not work" - is this upnp version or chromecast version? where are you playing from? What are your players?

**Comment by gldrenthe89** [comment]
@philippe44 I don't have it curruntly installed. I was using an iPhone 7 with iOS 11.3.1 using AirCast to stream to a Chromecast Soundbar from LG (LG SH7). If you want a log i can try. How do ik get the Log?

**Comment by philippe44** [comment]
just add "-f log.txt" to the command line and send me the file log.txt. But if you don't intend to really use it, maybe we should not worry

**Comment by gldrenthe89** [comment]
@philippe44 offcourse i wanna use it. But i have a clean installation of Ubuntu in a VM tot test. After shutdown the VM is restore to the snapshot before installation. If everything works. It'l get installed on a new VM specifically and only for this. When i have time i will check the log file en post it here

**Comment by gldrenthe89** [comment]
see attachement for log. running the app on clean ubuntu install 16.04 lts
[log.txt](https://github.com/philippe44/AirConnect/files/1985235/log.txt)

**Comment by philippe44** [comment]
your VM is on x86? and you see exactly the same problem on the Pi and on the x86 VM?

**Comment by gldrenthe89** [comment]
It is a x64 system. And yes. On a clean rpi2b have the same problem. I did not make a log of that

**Comment by philippe44** [comment]
It looks as if the CC players are not sending their mDNS keep-alive, or it is not received. I've seen that on network where a router/bridge is filtering out multicast packets. What is your network topology and what type of router do you have?

**Comment by gldrenthe89** [comment]
@philippe44 in have mDNS turned of in my USG (Unifi). i wil turn this on now en test again.

**Comment by gldrenthe89** [comment]
@philippe44 still the stream stops. took al bit more time now. Hope you see what is happening. See attached log
[log3.txt](https://github.com/philippe44/AirConnect/files/1997837/log3.txt)

**Comment by tomaash** [comment]
I have the same problem with version 0.2.1 and RBPi Zero W. I start playing on chromecast and after 10 seconds or so `aircast-arm` binary logs "DeleteCastDevice" and terminates. 
[arconnect-log.txt](https://github.com/philippe44/AirConnect/files/2062711/arconnect-log.txt)

**Comment by philippe44** [comment]
Thanks - It usually means that the multicast packet that is sent by the CC devices for presence renewal are filtered out by some router/bridge/switch in your network, so after a few seconds, the CC is considered gone. Look for multicast-related options, that should solve the problem. It's also frequent between different physical segments of your network (i.e. the wired and wireless on) and it's not visible when using your Android phone to control the CC because they are both on the wireless segment. I think there is a comment about that is the readme - hope this helps

**Comment by philippe44** [comment]
no, there is no crash. The addition/deletion of devices does not uses openSSL. It's a mDNS-SD search, and every service broadcasted by devices has a timeout and should send a renewal before it expires. I also send a global discovery request every 20s. So it's a device going silent wrt mDNS-SD

**Comment by tomaash** [comment]
Interesting. I also use the chromecasts directly, and they never disappear. I have a UPC router which may or may not filter multicast, but it's probably impossible to modify the settings. I wonder if there is a way to make airconnect work on a network like this in case I wouldn't be able to disable the multicast filtering.

**Comment by tomaash** [comment]
OK, so it's just me being stupid :) So the problem was that I didn't use the `-z` command line flag when running the binary with `ExecStart` parameter of `systemd`. As it has the `Restart=on-failure` and  `RestartSec=30` parameters as well, it will kill the binary after 30 seconds because it fails to daemonize. @gldrenthe89 I suspect that this might help you as well. Not AirConnect issue, but generic linux noob / rtfm issue. @philippe44 thanks for the awesome work!

**Comment by philippe44** [comment]
@tomaash glad you foudn the problem. @ghost it really looks like a mDNS issue of some sort and your network is not letting such multicast packet being sent on the different segments

**Comment by philippe44** [comment]
Closed for inactivity
