### ISSUE TITLE
new MediaRenderer string to be added

### ISSUE THREAD

**Issue by meiser79** [philippe44/AirConnect#90]
Hi,

my AndroidTV (Philips 43PUS6501/12) uses the MediaRenderer URN "urn:schemas-upnp-org:device:MediaRenderer:3".

Could you please add _urn:schemas-upnp-org:device:MediaRenderer:2_ and _urn:schemas-upnp-org:device:MediaRenderer:3_ as additional possible MediaRenderer strings?

Here a diff to replace the original string as a proof of concept:
```
diff --git a/airupnp/src/airupnp.c b/airupnp/src/airupnp.c
index 096d693..d04caf5 100644
--- a/airupnp/src/airupnp.c
+++ b/airupnp/src/airupnp.c
@@ -90,7 +90,7 @@ typedef struct sUpdate {
 /*----------------------------------------------------------------------------*/
 /* consts or pseudo-const                                                                                                        */
 /*----------------------------------------------------------------------------*/
-static const char      MEDIA_RENDERER[]        = "urn:schemas-upnp-org:device:MediaRenderer:1";
+static const char      MEDIA_RENDERER[]        = "urn:schemas-upnp-org:device:MediaRenderer:3";
 
 static const struct cSearchedSRV_s
 {
```

I verified the patch by hex-editing the x86 binary. After the modification, my DLNA renderer was found.

**Comment by philippe44** [comment]
Unfortunately I can't just do that, this would break compatibility with most devices. When searching for devices, at least with libupnp which is what I'm using, you must specify the version and I can't send 3 searches. I'll see if there is another solution.

**Comment by meiser79** [comment]
No explanation, just closing the ticket?

**Comment by philippe44** [comment]
I gave the explanation previously. I can't do that for a compatibility issue.

**Comment by meiser79** [comment]
With latest changes, could you also add
UpnpSearchAsync(glControlPointHandle, DISCOVERY_TIME, MEDIA_RENDERER ":3", NULL); ?

Thanks, meiser

**Comment by Hofyyy** [comment]
Hey,

do we know which devices use media renderer with version 1,2,3?
And does a media renderer needs other interface features depending on the version?

From my point of view the patch looks good. But I am also not a friend of too much network traffic.
So maybe something for the configuration, where we can specify a list of version which should be searched?

Best regards

**Comment by meiser79** [comment]
Sorry, I don't know the details regarding the versions. I just checked the network traffic and found out that my AndroidTV uses :3.

**Comment by Hofyyy** [comment]
I checked the upnp specs.
For me it seems to be that it is only a spec updates, see links to the specifications.
A newer specification then v3 is not available. So it would be correct to search v1,v2,v3 from my current knowledge.

@meiser79 
Because I still struggle with the compile ... did you try to remove the version, so that we will find all media renderer?
If possible that would be the nicer way or? http://manual.freeshell.org/libupnp-1.6.18/html/upnp/UpnpSearchAsync.html

Links:
http://upnp.org/specs/av/UPnP-av-MediaRenderer-v1-Device.pdf                              (2002)
http://upnp.org/specs/av/UPnP-av-AVArchitecture-v2.pdf                                            (2008)
http://www.upnp.org/specs/av/UPnP-av-MediaRenderer-v3-Device-20101231.pdf (2010)

**Comment by meiser79** [comment]
I also can't compile it.

**Comment by philippe44** [comment]
I've made the level of UPnP a parameter now
